pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'freetest(7e2121a4-8c0f-4bca-b0a8-567741a28fe6)'
    scriptLocation: inlineScript
    inlineScript: |
      az extension add -y --name spring-cloud
      az configure --defaults group=default-group
      az configure --defaults spring-cloud=spring-test
      az spring-cloud app create gateway
      az spring-cloud app create account-service
      az spring-cloud app create auth-service
      az spring-cloud app deploy -n gateway --jar-path ./gateway/target/gateway.jar
      az spring-cloud app deploy -n account-service --jar-path ./account-service/target/account-service.jar
      az spring-cloud app deploy -n auth-service --jar-path ./auth-service/target/auth-service.jar
      az spring-cloud app update -n gateway --is-public true
      az spring-cloud app show --name gateway --query properties.url
      # deploy other app
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
